dist: trusty
sudo: required
language: go
go: 1.11
services:
  - docker
env:
  - GO111MODULE=on
install: make setup
script: make ci

after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - gem install fpm
  - which fpm
  - sudo apt-get update
  - sudo apt-get install --yes snapd rpm liblz4-dev
  - export PATH=/snap/bin:$PATH
  - which snap
  - sudo snap install snapcraft --candidate --classic
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
deploy:
  skip_cleanup: true
  provider: script
  script: curl -sL https://git.io/goreleaser | rvm 2.4.1 do bash
  on:
    tags: true
notifications:
  email: false
